### ISSUE TITLE
HEAD requests are failing

### ISSUE THREAD

**Issue by mstmustisnt** [vedi/restifizer-files#9]
```
Unhandled rejection TypeError: Cannot read property 'stream' of undefined
2017-12-11T13:10:01.197117+00:00 app[web.1]:     at PostFileController.sendResult (/app/node_modules/restifizer-files/lib/file-controller.js:218:29)
2017-12-11T13:10:01.197118+00:00 app[web.1]:     at Bb.try.then.catch.then (/app/node_modules/restifizer-files/lib/file-controller.js:118:28)
2017-12-11T13:10:01.197118+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2017-12-11T13:10:01.197119+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2017-12-11T13:10:01.197122+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
2017-12-11T13:10:01.197122+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
2017-12-11T13:10:01.197123+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
2017-12-11T13:10:01.197124+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
2017-12-11T13:10:01.197124+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
2017-12-11T13:10:01.197125+00:00 app[web.1]:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
2017-12-11T13:10:01.197126+00:00 app[web.1]:     at runCallback (timers.js:789:20)
2017-12-11T13:10:01.197127+00:00 app[web.1]:     at tryOnImmediate (timers.js:751:5)
2017-12-11T13:10:01.197127+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by EugeneButusov** [comment]
I think something like this should be added: https://github.com/vedi/restifizer/blob/7241490926e168d10dd8624625be15a6b341aa1e/lib/transports/express.transport.js#L102

around this https://github.com/vedi/restifizer-files/blob/master/lib/file-controller.js#L218
